language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  # install dependencies
  - sudo pip install cython
  - sudo apt-get install python-ipy

  # install js libraries - not needed at this point
  #- sudo add-apt-repository 'deb http://ftp.nl.debian.org/debian/ jessie main'
  #- sudo add-apt-repository 'deb http://ftp.nl.debian.org/debian/ jessie-updates main'
  #- sudo add-apt-repository 'deb http://security.debian.org/ jessie/updates main'
  #- sudo apt-get update
  #- sudo apt-get install libjs-modernizr --force-yes
  #- sudo apt-get install libjs-jquery --force-yes
  #- sudo apt-get install libjs-twitter-bootstrap --force-yes

  # build streamhtmlparser and python module
  - cd streamhtmlparser
  - ./configure
  - make
  - sudo make install
  - cd src/py-streamhtmlparser
  - make
  - sudo make install
  - cd ../../../

  # put streamhtmlparser in the proper environment
  - sudo cp /usr/local/lib/python2.7/dist-packages/* /usr/lib/python2.7/dist-packages
  - sudo ldconfig -v

  # build runtime environment
  - sudo mkdir /var/log/swiperproxy
  - sudo addgroup --system swiperproxy
  - sudo adduser --system swiperproxy --ingroup=swiperproxy --no-create-home
  - sudo chown -R swiperproxy:swiperproxy swiperproxy
  - sudo chown swiperproxy:swiperproxy /var/log/swiperproxy

  # set cap to bind to ports < 1024
  - sudo apt-get install libcap2-bin
  - setcap 'cap_net_bind_service=+ep' swiperproxy/Proxy.py

script:
  - sudo -u swiperproxy python Proxy.py -c proxy.conf
