language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - sudo apt-get install cython
  - sudo apt-get install python-ipy
  - sudo add-apt-repository 'deb http://ftp.nl.debian.org/debian/ jessie main'
  - sudo add-apt-repository 'deb http://ftp.nl.debian.org/debian/ jessie-updates main'
  - sudo add-apt-repository 'deb http://security.debian.org/ jessie/updates main'
  - sudo apt-get update
  - sudo apt-get install libjs-modernizr --force-yes
  - sudo apt-get install libjs-jquery --force-yes
  - sudo apt-get install libjs-twitter-bootstrap --force-yes
  - wget https://streamhtmlparser.googlecode.com/files/streamhtmlparser-0.1.tar.gz
  - tar -zxvf streamhtmlparser-0.1.tar.gz
  - cd streamhtmlparser-0.1 && ./configure && make && sudo make install
  - cd ..

script:
  - python Proxy.py
